### ISSUE TITLE
Synch rake problem

### ISSUE THREAD

**Issue by kryna** [BadrIT/translation_center#53]
``` code
kryna@kryna-ubuntu:~/Projekty/sa8000$ rake translation_center:synch
3 locales available: en, ar, de
1520 unique keys found.
An error has ocurred while performing this rake, would you like to send the exception to us so we may fix this problem ? press [Y/n]
y
Sending ...
We have received your feedback. Thanks!
allocator undefined for Proc
/home/kryna/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych/visitors/to_ruby.rb:303:in `allocate'
/home/kryna/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych/visitors/to_ruby.rb:303:in `revive'
/home/kryna/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych/visitors/to_ruby.rb:178:in `visit_Psych_Nodes_Mapping'
/home/kryna/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych/visitors/visitor.rb:15:in `visit'
/home/kryna/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych/visitors/visitor.rb:5:in `accept'
/home/kryna/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych/visitors/to_ruby.rb:20:in `accept'
/home/kryna/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych/visitors/to_ruby.rb:240:in `visit_Psych_Nodes_Document'
/home/kryna/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych/visitors/visitor.rb:15:in `visit'
/home/kryna/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych/visitors/visitor.rb:5:in `accept'
/home/kryna/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych/visitors/to_ruby.rb:20:in `accept'
/home/kryna/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych/nodes/node.rb:35:in `to_ruby'
/home/kryna/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych.rb:130:in `load'
```

**Comment by seanfcarroll** [comment]
Can this be closed?
