### ISSUE TITLE
 undefined method `prepare_key'

### ISSUE THREAD

**Issue by LaurensN** [BadrIT/translation_center#72]
After bundle install, migrations, when starting server or console I get the following error:

/translation_helpers.rb:60:in `translate_with_adding': undefined method `prepare_key' for #<I18n::Backend::Simple:0x007f8ba7554d50> (NoMethodError)

Rails 4.2.4

**Comment by LaurensN** [comment]
This can be fixed by including it in I18n::Backend::Simple:

https://github.com/BadrIT/translation_center/compare/master...LaurensN:master

**Comment by seanfcarroll** [comment]
I'm having the same problem on branch https://github.com/hzbadr/translation_center/pull/2

```
rake translation_center:synch
rake aborted!
NoMethodError: undefined method `prepare_key' for #<I18n::Backend::Simple:0x007fbfc2ae0978>
/Users/sean/src/seanfcarroll/immersive/app/admin/dashboard.rb:1:in `<top (required)>'
/Users/sean/src/seanfcarroll/immersive/config/routes.rb:12:in `block (2 levels) in <top (required)>'
/Users/sean/src/seanfcarroll/immersive/config/routes.rb:9:in `block in <top (required)>'
/Users/sean/src/seanfcarroll/immersive/config/routes.rb:3:in `<top (required)>'
/Users/sean/src/seanfcarroll/immersive/config/environment.rb:6:in `<top (required)>'
```

**Comment by seanfcarroll** [comment]
This was caused by a conflict with ActiveAdmin

**Comment by seanfcarroll** [comment]
Solved by adding this to an initializer

```
I18n::Backend::Simple.send(:include, TranslationCenter)
```

Don't really understand why this is necessary
